steps:
  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/execcorp-website:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/execcorp-website:latest',
      '.'
    ]

  # Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/execcorp-website:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/execcorp-website:latest']

  # Deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'execcorp-website',
      '--image', 'gcr.io/$PROJECT_ID/execcorp-website:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '3000',
      '--memory', '512Mi',
      '--cpu', '1',
      '--max-instances', '10',
      '--min-instances', '0',
      '--concurrency', '80',
      '--timeout', '300'
    ]

images:
  - 'gcr.io/$PROJECT_ID/execcorp-website:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/execcorp-website:latest'

options:
  logging: CLOUD_LOGGING_ONLY 